AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Storybook Hosting
Resources:
  StorybookBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html

  PublisherUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-Publisher

  StorybookBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StorybookBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StorybookBucket}/*"
          - Sid: PublisherAndAdminPermissions
            Effect: Allow
            Action:
              - s3:*
            Resource:
              - !Sub arn:aws:s3:::${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
              - !Sub arn:aws:s3:::${AWS::StackName}-${AWS::AccountId}-${AWS::Region}/*
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:role/Admin
                - !Sub arn:aws:iam::${AWS::AccountId}:role/ResearchAdmin
                - !GetAtt PublisherUser.Arn