name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 16 With Yarn Cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
      - name: Configure Git User
        run: |
          git config --global user.email "eresearch@qut.edu.au"
          git config --global user.name "@$GITHUB_ACTOR"
      - name: Configure NPMRC
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: eresearchqut
        env:
          AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
      - name: Build Package
        run: |
          yarn install
          yarn build
          yarn lerna publish minor --no-changelog --conventional-commits --yes