name: Build and Publish Storybooks
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: 'yarn'
        run: |
          yarn install
          yarn build
          yarn build-storybooks
      - name: publish storybooks
        uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            branch: gh-pages
            folder: storybooks
