name: Build and Publish Storybook
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node 16 With Yarn Cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'
      - name: Build Story Book
        run: |
          yarn install
          yarn build-nocache
          yarn storybook-build
      - name: Publish Story Book
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.STORYBOOK_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'storybook-static'
          DEST_DIR: ${GITHUB_REF##*/}